spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mentoring?useSSL=false&serverTimezone=UTC
    username: ksh
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 80

jwt:
  issuer: tigertjdgh@gmail.com
  secret_key: ksh-mentoring
